### ISSUE TITLE
Josh Providers Checks

### ISSUE THREAD

**Issue by WilsontheWolf** [josh-development/core#22]
*This discussion originally started in the discord server*.
Right now JOSH checks if a value exists in the get method (and probably more) using has. However, in a network-based solution (such as the HTTP, or MongoDB providers) it takes longer to do requests. Let's say it takes 100ms to make a request, and you have to make a request for both has and get. This would take you 200ms to get this data. 
Now let's say that the server already does this check on the get method. Then not only do you do a redundant check and its costing time. 
The providers can easily throw this check in, and, this allows more adaptivity in the future.

**Comment by JOSH-Javascript-Object-Storage-Handler** [comment]
josh approved

###### i am not affiliated with evie, however i made this account because *yes*
